config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "lists#index"
  resources :lists, except: [:edit, :update] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: :destroy
end



  # root to: "lists#index":

  # This line sets the root or homepage route of your application.
  # It maps the root URL ("/") to the index action of the ListsController.

  # resources :lists, except: [:edit, :update] do:

  # This line establishes the resourceful routes for the List model.
  # The resources method automatically generates routes for all the default CRUD actions
  # However, the except option is used to exclude the edit and update actions from being generated.

  # The do...end block is used to nest additional routes within the lists resource.

  # resources :bookmarks, only: [:new, :create]:

  # This line establishes resourceful routes for the Bookmark model nested within the List model.
  # It generates routes for the new and create actions of the BookmarksController, specifically for the context of a specific List.

  # resources :bookmarks, only: :destroy:

  # This line establishes resourceful routes for the Bookmark model.
  # It generates a route for the destroy action of the BookmarksController.

  # The resources method automatically generates routes based on the RESTful conventions, which map HTTP verbs and URLs to controller actions.
  # By defining these routes, you can handle requests to different URLs and perform the appropriate actions
  # in your controllers. The routes file serves as a central configuration for mapping incoming requests
  # to the corresponding controllers and actions in your Rails application.


  # The reason why resources :bookmarks, only: :destroy is placed outside the do...end block for lists is that it
  # represents a separate resource that is not directly related to the List model.

  # Here's the rationale behind the placement:

  # resources :lists, except: [:edit, :update] do ... end:

  # This block establishes a nested resource relationship between lists and bookmarks within the do...end block.
  # It indicates that bookmarks are associated with lists and should be nested under lists in the URL structure.
  # The nested routes, such as lists/:list_id/bookmarks, imply that bookmarks are scoped within the context of a specific list.

  # resources :bookmarks, only: :destroy:

  # This line is placed outside the do...end block to define routes for the Bookmark model that are not nested within a specific List.
  # It generates a route for the destroy action of the BookmarksController that operates independently of any particular List.
  # The URL for destroying a bookmark might be something like /bookmarks/:id, not /lists/:list_id/bookmarks/:id.
  # By separating the resources :bookmarks, only: :destroy line from the do...end block,
  # you allow for both nested and non-nested routes related to bookmarks.
  # This structure provides flexibility and allows you to handle bookmarks within the context of a list,
  # as well as bookmarks independently.

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks, dependent: :destroy

  validates :name, uniqueness: true, presence: true
end


# has_many :bookmarks, dependent: :destroy:

#   This line establishes a one-to-many association between the List model and the Bookmark model.
#   It indicates that a list can have multiple bookmarks associated with it.
#   The dependent: :destroy option specifies that if a list is destroyed, all associated bookmarks should also be destroyed.

# has_many :movies, through: :bookmarks, dependent: :destroy:

#   This line establishes a many-to-many association between the List model and the Movie model.
#   It indicates that a list can have multiple movies associated with it through the Bookmark model.
#   The dependent: :destroy option specifies that if a list is destroyed,
#   all associated bookmarks (and indirectly, the associated movies) should also be destroyed.

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :destroy]

  def index
    @lists = List.all
  end

  def show
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list.destroy
    redirect_to lists_path, status: :see_other
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end


# def show
#   @bookmark = Bookmark.new
# end

# This code is responsible for handling the show action when a user requests to view a specific list.

# Inside the show method, a new instance of the Bookmark model is created and assigned to the instance variable @bookmark.
# By initializing a new Bookmark object, you're likely preparing to use it in the view associated with the show action.
# It's common to use this approach to enable users to add new bookmarks related to the displayed list.
# By creating a new Bookmark instance in this action, you can then pass it to the view,
# allowing you to generate a form or provide a way for users to interact with bookmarks specific to the displayed list.
# Essentially, this code is preparing an instance of the Bookmark model in the show action,
# likely to enable the creation of new bookmarks associated with the current list being displayed.


# In your lists_controller.rb, the list_params method is defined to permit and extract specific parameters from the params hash.
# This method is typically used to ensure that only the allowed parameters are passed when creating or updating a list.

# def create
#   @list = List.new(list_params)
#   if @list.save
#     redirect_to list_path(@list)
#   else
#     render :new, status: :unprocessable_entity
#   end
# end

# In the create method, a new instance of the List model is created. The list_params method is then invoked to extract the permitted parameters
# and assign them to the newly created @list object.

# def list_params
#   params.require(:list).permit(:name, :photo)
# end

# The list_params method is a private method that permits and extracts the parameters necessary
# for creating or updating a list.

# params.require(:list) specifies that the params hash must contain a key called :list.
# This ensures that the parameters passed for creating or updating a list must be nested under the :list key.

# .permit(:name, :photo) allows the :name and :photo attributes to be accessed from the permitted parameters.
# Only these attributes will be allowed, and any other parameters will be ignored for security reasons.
# This prevents unwanted or malicious parameters from being processed.

# By using the list_params method, you enforce strong parameters and ensure that only the permitted attributes are used for creating or updating a list,
# which helps protect your application from potential security risks.

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/index.html.erb
<div class="cover mb-4 d-flex align-items-center justify-content-center">
  <div class="text-center text-white">
    <h1>Bookmark Movies for Future Viewing!</h1>
    <h3 class="typed-js" data-controller="typed-js"></h3>
  </div>
</div>

<div class="container py-5">
  <div class="d-flex align-items-center justify-content-between mb-3">
    <h3 class="mb-0">My Lists</h3>
    <%= link_to "create a movie list", new_list_path, class: "btn btn-flat text-dark" %>
  </div>

  <div class="row">
    <% @lists.each do |list| %>
      <div class="col-12 col-sm-6 col-md-4 mb-3">
        <%= link_to list_path(list), class: "text-decoration-none" do %>
          <div class="card card-category">
            <%= list.name %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<div class="new-list-container">
  <div class="new-list-form">
    <h3>Create a new list</h3>
    <%= simple_form_for @list do |f| %>
      <%= f.input :name, placeholder: 'Drama' %>
      <%= f.submit class: 'btn btn-flat' %>
    <% end %>
  </div>
</div>

app/views/lists/show.html.erb
<div class="position-relative">
  <div class="card-category card-large" %>
    <h1 class="text-center text-dark"><%= @list.name %></h1>
  </div>
  <span class="movie-tag"><%= pluralize(@list.movies.size, "movie") %></span>
</div>
<div class="container mb-5">
  <div class="d-flex justify-content-between my-4">
    <span class="mb-2 d-block"><small><em class="text-dark"><%= "You haven't pinned any movies yet!" if @list.movies.empty? %></em></small></span>
    <div>
      <button type="button" class="btn btn-flat text-dark" data-bs-toggle="modal" data-bs-target="#new_movie_modal">
        add a movie
      </button>
      <%= link_to "delete this list", list_path(@list), class: "btn btn-cancel text-dark", data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this list?" } %>
      <%= link_to "see all lists", lists_path, class: "btn btn-flat text-dark" %>
    </div>
  </div>
  <div class="row my-2">
    <% @list.movies.each do |movie| %>
      <% bookmark = Bookmark.find_by(list: @list, movie: movie) %>
      <div class="col-12 col-sm-6 mb-4" data-aos="zoom-in">
        <div class="bg-white rounded shadow h-100">
          <%= image_tag movie.poster_url, alt: movie.title, class: "movie-img rounded-top" %>
          <div class="p-3 rounded-bottom d-flex flex-column">
            <strong><%= movie.title %> <span class="text-muted font-weight-normal">• <%= movie.rating %> <i class="fas fa-star star-yellow"></i></span></strong>
            <small class="text-muted"><%= movie.overview %></small>
            <div class="d-flex align-items-end justify-content-between pt-4">
              <div>
                <i class="fas fa-quote-left me-2"></i><small class="flex-grow-1"><%= bookmark.comment %></small>
              </div>
              <small class="text-right flex-shrink-0"><%= link_to "delete", bookmark_path(bookmark), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to remove #{movie.title} from your #{@list.name} list"}, class: 'text-danger' %></small>
            </div>
          </div>
        </div>
      </div>
    <% end %>
<%= render "bookmarks/modal", list: @list, bookmark: @bookmark %>




<%# <% @list.movies.each do |movie| %>
<%# This line starts a loop that iterates over each movie in the movies association of the @list object.
The do |movie| part defines a block variable movie that represents each iteration. %>

<%# <% bookmark = Bookmark.find_by(list: @list, movie: movie) %>
<%# This line finds a Bookmark object using the find_by method.
It searches for a bookmark where the list attribute matches @list and the movie attribute matches the current movie iteration variable.
The resulting Bookmark object is assigned to the bookmark variable. %>

<%# <%= image_tag movie.poster_url, alt: movie.title, class: "movie-img rounded-top" %>
<%# This line generates an HTML <img> tag using the image_tag helper method.
It displays the movie's poster image using the poster_url attribute of the movie object.
The alt attribute is set to the movie's title, and the class attribute applies styling classes to the image. %>

<%# <i class="fas fa-quote-left me-2"></i><small class="flex-grow-1"><%= bookmark.comment %>
<%# This line displays the bookmark's comment. It includes an icon using the Font Awesome library (fas fa-quote-left) and the comment itself,
which is the comment attribute of the bookmark object. %>

<%# <small class="text-right flex-shrink-0"><%= link_to "delete",
bookmark_path(bookmark), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to remove
#{movie.title} from your #{@list.name} list" }, class: 'text-danger'</small>
<%# This line generates a link to delete the bookmark. It uses the link_to helper method
to create an anchor tag (<a>) with the text "delete." The link's destination
is the bookmark_path for the given bookmark object. It also includes additional attributes using the data option, such
turbo_method for specifying a delete method and turbo_confirm for displaying a confirmation message.  %>